baseURL = "https://frothy.dev/"
languageCode = "en-us"
title = "Frothy"
relativeURLs = true
disableKinds = ["taxonomy", "term"]

[module]
  [[module.mounts]]
    source = "static"
    target = "static"
    excludeFiles = ["test/**"]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokailight"
    lineNos = false
    noClasses = false

[params]
  description = "A live lexical language for programmable devices."
